[package]
name = "leifstout/dataservice"
description = "Data handler and replication"
version = "0.4.0"
license = "MIT"
authors = ["Leif Stout <leifstout@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]
Signal = "sleitnick/signal@2.0.0"
Janitor = "howmanysmall/janitor@1.17.0"
Networker = "leifstout/networker@0.2.1"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"
